general.live_config_reload = true

[window]
opacity = 0.7

[font]
normal = { family = "Cascadia Mono" }
size = 11

[colors.primary]
background = "#000000"

[keyboard]
  [[keyboard.bindings]]
    key = "C"
    mods = "Control|Shift"
    action = "Copy"
